//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.WS_Sales {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Sales.WS_SalesSoap")]
    public interface WS_SalesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNewCostumer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertNewCostumer(string name, string surname, string email, string phone, string address, string website);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCostumerInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCostumerInfo(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCostumers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllCostumers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCostumerOrderHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCostumerOrderHistory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCustomerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddNewOrder(int id, string productName, int qty, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderByCostumer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrderByCostumer(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrderByDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrderList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLastOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllInvoices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllInvoices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastOrderNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLastOrderNum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetCat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetProducts(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategoryID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCategoryID(string cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetProductPrice(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomersList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetCustomersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerIdByFullName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCustomerIdByFullName(string name, string surnam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CreateNewBill(int cId, int eid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_SalesSoapChannel : Sales.WS_Sales.WS_SalesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_SalesSoapClient : System.ServiceModel.ClientBase<Sales.WS_Sales.WS_SalesSoap>, Sales.WS_Sales.WS_SalesSoap {
        
        public WS_SalesSoapClient() {
        }
        
        public WS_SalesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_SalesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SalesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SalesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertNewCostumer(string name, string surname, string email, string phone, string address, string website) {
            return base.Channel.InsertNewCostumer(name, surname, email, phone, address, website);
        }
        
        public System.Data.DataSet GetCostumerInfo(string name) {
            return base.Channel.GetCostumerInfo(name);
        }
        
        public System.Data.DataSet GetAllCostumers() {
            return base.Channel.GetAllCostumers();
        }
        
        public System.Data.DataSet GetCostumerOrderHistory(int id) {
            return base.Channel.GetCostumerOrderHistory(id);
        }
        
        public System.Data.DataSet GetCustomerList() {
            return base.Channel.GetCustomerList();
        }
        
        public string AddNewOrder(int id, string productName, int qty, string description) {
            return base.Channel.AddNewOrder(id, productName, qty, description);
        }
        
        public System.Data.DataSet GetOrderByCostumer(string name) {
            return base.Channel.GetOrderByCostumer(name);
        }
        
        public System.Data.DataSet GetOrderByDate(string date) {
            return base.Channel.GetOrderByDate(date);
        }
        
        public System.Data.DataSet GetOrderList() {
            return base.Channel.GetOrderList();
        }
        
        public string GetLastOrder() {
            return base.Channel.GetLastOrder();
        }
        
        public System.Data.DataSet GetAllInvoices() {
            return base.Channel.GetAllInvoices();
        }
        
        public string GetLastOrderNum() {
            return base.Channel.GetLastOrderNum();
        }
        
        public string[] GetCat() {
            return base.Channel.GetCat();
        }
        
        public string[] GetProducts(int id) {
            return base.Channel.GetProducts(id);
        }
        
        public string GetCategoryID(string cat) {
            return base.Channel.GetCategoryID(cat);
        }
        
        public string GetProductPrice(string name) {
            return base.Channel.GetProductPrice(name);
        }
        
        public string[] GetCustomersList() {
            return base.Channel.GetCustomersList();
        }
        
        public string GetCustomerIdByFullName(string name, string surnam) {
            return base.Channel.GetCustomerIdByFullName(name, surnam);
        }
        
        public int CreateNewBill(int cId, int eid) {
            return base.Channel.CreateNewBill(cId, eid);
        }
    }
}
